FROM node:8.10.0

RUN npm install -g npm
RUN npm install pm2 -g
RUN apt-get update
RUN apt-get install -y dnsutils
RUN apt-get install -y lsof
RUN apt-get install -y netcat
RUN apt-get install -y vim
